name: Powershell External Automation Demo
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Numero de versión instalador
        type: string
        required: true
      choice:
        type: choice
        description: BuildType
        options:
        - DEV
        - QA
        - REL
jobs:
  advinst-com-demo:
    runs-on: windows-latest
    name: Advinst Automation Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out repository customAction
        uses: actions/checkout@v4
        with:
          repository: fagustin/AIP
          token: ${{ secrets.GH_PAT }} # 'GH_PAT' is a secret that contains your PAT
          path: AIP/scr
          ref: 'main'
      - name: Check out repository customAction
        uses: actions/checkout@v4
        with:
          repository: fagustin/powershellscript
          token: ${{ secrets.GH_PAT }} # 'GH_PAT' is a secret that contains your PAT
          path: pwsh/scr
          ref: 'main'
      - name: prepare directory
        run: |
          mkdir ${{ github.workspace }}\CustomActions
          cd  ${{ github.workspace }}\CustomActions
          xcopy ${{ github.workspace }}\AIP\scr\CustomActions ${{ github.workspace }}\CustomActions /s
          dir
          xcopy ${{ github.workspace }}\pwsh\scr ${{ github.workspace }} /s
      - name: Deploy Advinst
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '21.2.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
      - name: Use Advinst Automation
        shell: pwsh
        run: |
          ./FullPatchPostBuildEvent.ps1 -src_path "${{ github.workspace }}" -path_template "${{ github.workspace }}\POCv2.aip" -version_installer "${{ inputs.version}}" -BuildType "${{ inputs.choice}}" -DBOrder "${{ github.workspace }}\Scripts" -IS_F2_TRANSITION "0"
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: ${{ github.workspace }}\Setup Files\POCv2${{ inputs.choice }}.exe
