name: Powershell Automation Demo
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Numero de versión instalador
        type: string
        required: true
      choice:
        type: choice
        description: BuildType
        options:
        - DEV
        - QA
        - REL
jobs:
  advinst-com-demo:
    runs-on: windows-latest
    name: Advinst Automation Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.1
      - name: Deploy Advinst
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '21.2.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
      - name: Use Advinst Automation
        shell: pwsh
        run: |
          # Load the AIP project from checkout location
          $aipPath = join-path $env:GITHUB_WORKSPACE "POCv2.aip";
          Write-Host "AIP: $aipPath";
          $advinst = new-object -com advancedinstaller;
          $project = $advinst.LoadProject($aipPath);
          $productDetails = $project.ProductDetails;
          # Bump the ProductVersion
          $productDetails.Version = "${{ inputs.version}}";
          Write-Host "Version: $productDetails.Version";
          $aboutProp = $project.PropertyComponent.FindProperty("GLOBAL_VERSION")
          $aboutProp.value = "GLOBAL_VERSION_VALUE_TEST"
          AdvancedInstaller /edit  $aipPath /SetPackageName "DS50Patch$version${{ inputs.choice}}"
          # Build the project
          $project.Build();
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: ${{ github.workspace }}\Setup Files\POCv2.exe
